project:
  type: website

website:
  title: "shinigami-777's Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - Spacelab
    css: styles.css
    toc: true



