name: Quarto Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("quarto"))'

      - name: List files (debug step)
        run: ls -lR

      - name: Render site
        working-directory: blog
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: blog/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
